export const DealService = {
  getDealsData() {
    return [
      {
        id: "1000",
        dealName: "BANFF_FD Team",
        therapeuticArea: "CRM",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
        isOwner: true,
      },
      {
        id: "1001",
        dealName: "BANFF_FD Team",
        therapeuticArea: "CRM",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1002",
        dealName: "BANFF_FD Team",
        therapeuticArea: "AB",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1003",
        dealName: "BANFF_FD Team",
        therapeuticArea: "AB",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1004",
        dealName: "BANFF_FD Team",
        therapeuticArea: "CD",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1005",
        dealName: "BANFF_FD Team",
        therapeuticArea: "CD",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1006",
        dealName: "BANFF_FD Team",
        therapeuticArea: "SR",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1007",
        dealName: "BANFF_FD Team",
        therapeuticArea: "SR",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1008",
        dealName: "BANFF_FD Team",
        therapeuticArea: "CRM",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
      {
        id: "1009",
        dealName: "BANFF_FD Team",
        therapeuticArea: "CRM",
        dealStage: "Triange",
        modifiedBy: "Ravi Chaudhary",
        dateModified: "Aug 27 2024",
        dealLead: "Kunal Dhar",
      },
    ];
  },

  getDeals() {
    return Promise.resolve(this.getDealsData());
  },
};
